# Generated by Django 5.1.6 on 2025-02-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='password',
            field=models.CharField(default='default_password', max_length=20),
        ),
    ]
