# Generated by Django 5.1.6 on 2025-02-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neo', '0002_contact_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
